import type { Lang } from "./types";

export const ROUTES = [
  { href: "/map", key: "map" },
  { href: "/projects", key: "projects" },
  { href: "/compare", key: "compare" },
  { href: "/market", key: "market" },
  { href: "/developers", key: "developers" },
  { href: "/roi", key: "roi" },
] as const;

export const copy = {
  en: {
    nav: ["Map", "Projects", "Compare", "Market", "Developers", "Calculator"],
    menu: "Menu",
    close: "Close",
    home: "Home",
    eyebrow: "Dubai off-plan intelligence",
    titleA: "See the deal.",
    titleB: "Not the sales pitch.",
    intro:
      "Search, filter and compare Dubai off-plan projects using one structured market reference.",
    explore: "Explore projects",
    compare: "Compare projects",
    search: "Search by project, developer or area",
    allAreas: "All areas",
    allDevelopers: "All developers",
    projects: "Projects",
    developers: "Developers",
    areas: "Area benchmarks",
    verified: "Escrow matched",
    comparison: "Live comparison",
    comparisonSub: "Select up to 5 projects. The clearest differences stay visible.",
    emptyCompare: "Add projects from the projects page to start comparing.",
    goToProjects: "Go to projects",
    market: "Dubai area benchmarks",
    marketSub: "Indicative reference points from the workbook, not a valuation.",
    developerTitle: "Developer scorecard",
    developerSub: "A structured view of delivery, quality and safety.",
    leadTitle: "Need a shortlist built around your budget?",
    leadSub: "Share the basics and Mashhour Real Estate will prepare a focused comparison.",
    send: "Request a shortlist",
    success: "Thank you — your request is ready for follow-up.",
    mapTitle: "Dubai project map",
    mapSub: "Explore mapped communities, then open any project for the complete record.",
    mapMapped: "SELECTED AREA",
    mapHint: "Select a project cluster on the map.",
    mapEmpty: "Pins use community centres and are indicative, not plot boundaries.",
    loading: "Loading market data…",
    results: "results",
    loadMore: "Load more projects",
    viewDetails: "View details",
    addCompare: "Compare",
    selected: "Selected",
    maxSelected: "5 selected",
    exploreSections: "Explore the platform",
    exploreSectionsSub: "Each section now has its own page.",
    sectionBlurbs: {
      map: "Locate every mapped community across Dubai.",
      projects: "Search and filter the full off-plan database.",
      compare: "Put up to five projects side by side.",
      market: "Benchmark price per square foot and yields.",
      developers: "Delivery, quality and safety scores.",
      roi: "Model ROI, ROE and payback on any unit.",
    },
    name: "Name",
    phone: "Phone",
    email: "Email",
    budget: "Budget",
    footerLine: "Dubai off-plan comparison & market intelligence.",
    roiTitle: "ROI & ROE calculator",
    roiSub: "Change the inputs and every result updates instantly.",
    calcInputs: "Property inputs",
    calcAreaSqft: "Area (sq ft)",
    calcPricePerSqft: "Price per sq ft (AED)",
    calcRentPerSqft: "Annual rent per sq ft (AED)",
    calcAppreciation: "Expected appreciation (%)",
    calcExpenses: "Annual expenses (optional)",
    calcUseBenchmark: "Prefill from an area benchmark",
    calcPlan: "Payment plan",
    calcStage: "Stage",
    calcPercent: "%",
    calcAmount: "Amount",
    calcEquity: "Counts as equity",
    calcAddStage: "Add stage",
    calcRemove: "Remove",
    calcTotal: "Total",
    calcPlanOk: "Payment plan adds up ✓",
    calcPlanError: "The payment plan must total 100%",
    calcSummary: "Investment summary",
    calcPrice: "Property price",
    calcAnnualRent: "Annual rent",
    calcNetRent: "Net annual rent",
    calcProjected: "Projected value (1Y)",
    calcGain: "Capital gain",
    calcReturns: "Returns & projection",
    calcRoi: "ROI — rental yield",
    calcEquityPaid: "Paid equity",
    calcRoe: "ROE — return on equity",
    calcTotalReturn: "Total return year 1",
    calcPayback: "Payback period",
    calcYears: "years",
    calcReset: "Reset to defaults",
    calcFormulas: "How it is calculated",
    calcF1: "Price = Area × Price per sq ft",
    calcF2: "Annual rent = Area × Annual rent per sq ft",
    calcF3: "ROI = Net rent ÷ Property price",
    calcF4: "ROE = Net rent ÷ Paid equity",
    calcF5: "Payback = Paid equity ÷ Net rent",
    calcNote: "Indicative modelling only. Verify prices, rents and payment terms with the developer before advising a client.",
    articlesProjects: "Project insights",
    articlesDevelopers: "Developer insights",
    articlesAreas: "Area insights",
  },
  ar: {
    nav: ["الخريطة", "المشاريع", "المقارنة", "السوق", "المطورون", "الحاسبة"],
    menu: "القائمة",
    close: "إغلاق",
    home: "الرئيسية",
    eyebrow: "مرجع الأوف بلان في دبي",
    titleA: "شوف الصفقة.",
    titleB: "مش كلام المبيعات.",
    intro: "ابحث وفلتر وقارن مشاريع دبي الأوف بلان من قاعدة بيانات منظمة واحدة.",
    explore: "استكشف المشاريع",
    compare: "قارن المشاريع",
    search: "ابحث بالمشروع أو المطور أو المنطقة",
    allAreas: "كل المناطق",
    allDevelopers: "كل المطورين",
    projects: "مشروع",
    developers: "مطور",
    areas: "مؤشر منطقة",
    verified: "حساب ضمان مطابق",
    comparison: "مقارنة مباشرة",
    comparisonSub: "اختار لحد 5 مشاريع وشوف الفروق الأساسية بوضوح.",
    emptyCompare: "ضيف مشاريع من صفحة المشاريع علشان تبدأ المقارنة.",
    goToProjects: "روح لصفحة المشاريع",
    market: "مؤشرات مناطق دبي",
    marketSub: "مؤشرات استرشادية من الشيت وليست تقييمًا عقاريًا.",
    developerTitle: "تقييم المطورين",
    developerSub: "نظرة منظمة على التسليم والجودة والأمان.",
    leadTitle: "محتاج قائمة مشاريع مناسبة لميزانيتك؟",
    leadSub: "سيب بياناتك وMashhour Real Estate يجهز لك مقارنة مركزة.",
    send: "اطلب القائمة",
    success: "شكرًا — طلبك جاهز للمتابعة.",
    mapTitle: "خريطة مشاريع دبي",
    mapSub: "استكشف المناطق واضغط على أي مشروع لفتح كل بياناته.",
    mapMapped: "المنطقة المختارة",
    mapHint: "اختار تجمع مشاريع من الخريطة.",
    mapEmpty: "النقاط في مراكز المناطق استرشادية وليست حدود قطع الأراضي.",
    loading: "جاري تحميل بيانات السوق…",
    results: "نتيجة",
    loadMore: "عرض مشاريع أكثر",
    viewDetails: "عرض التفاصيل",
    addCompare: "قارن",
    selected: "تمت الإضافة",
    maxSelected: "5 مختارة",
    exploreSections: "استكشف المنصة",
    exploreSectionsSub: "كل قسم أصبح له صفحة مستقلة.",
    sectionBlurbs: {
      map: "حدد كل المناطق على خريطة دبي.",
      projects: "ابحث وفلتر قاعدة بيانات الأوف بلان كاملة.",
      compare: "قارن حتى خمسة مشاريع جنبًا إلى جنب.",
      market: "مؤشرات سعر القدم والعائد لكل منطقة.",
      developers: "درجات التسليم والجودة والأمان.",
      roi: "احسب ROI وROE وفترة الاسترداد لأي وحدة.",
    },
    name: "الاسم",
    phone: "رقم الهاتف",
    email: "البريد الإلكتروني",
    budget: "الميزانية",
    footerLine: "مقارنة مشاريع دبي الأوف بلان ومؤشرات السوق.",
    roiTitle: "حاسبة ROI و ROE",
    roiSub: "غيّر المدخلات وكل النتائج هتتحدث فورًا.",
    calcInputs: "بيانات الوحدة",
    calcAreaSqft: "المساحة (قدم²)",
    calcPricePerSqft: "سعر القدم (درهم)",
    calcRentPerSqft: "إيجار القدم السنوي (درهم)",
    calcAppreciation: "نسبة الزيادة المتوقعة (%)",
    calcExpenses: "مصاريف سنوية (اختياري)",
    calcUseBenchmark: "املأ من مؤشر منطقة",
    calcPlan: "خطة الدفع",
    calcStage: "المرحلة",
    calcPercent: "النسبة %",
    calcAmount: "المبلغ",
    calcEquity: "ضمن رأس المال",
    calcAddStage: "أضف مرحلة",
    calcRemove: "حذف",
    calcTotal: "الإجمالي",
    calcPlanOk: "خطة الدفع مضبوطة ✓",
    calcPlanError: "مجموع خطة الدفع لازم يساوي 100%",
    calcSummary: "ملخص الاستثمار",
    calcPrice: "سعر العقار",
    calcAnnualRent: "الإيجار السنوي",
    calcNetRent: "صافي الإيجار",
    calcProjected: "السعر المتوقع بعد سنة",
    calcGain: "الزيادة الرأسمالية",
    calcReturns: "العوائد والتوقعات",
    calcRoi: "ROI — عائد الإيجار",
    calcEquityPaid: "رأس المال المدفوع",
    calcRoe: "ROE — عائد رأس المال",
    calcTotalReturn: "العائد الكلي سنة 1",
    calcPayback: "فترة استرداد رأس المال",
    calcYears: "سنة",
    calcReset: "إعادة تعيين",
    calcFormulas: "طريقة الحساب",
    calcF1: "السعر = المساحة × سعر القدم",
    calcF2: "الإيجار السنوي = المساحة × إيجار القدم",
    calcF3: "ROI = صافي الإيجار ÷ سعر العقار",
    calcF4: "ROE = صافي الإيجار ÷ رأس المال المدفوع",
    calcF5: "فترة الاسترداد = رأس المال المدفوع ÷ صافي الإيجار",
    calcNote: "أرقام استرشادية فقط. راجع الأسعار والإيجارات وشروط الدفع مع المطور قبل تقديم أي نصيحة للعميل.",
    articlesProjects: "مقالات عن المشاريع",
    articlesDevelopers: "مقالات عن المطورين",
    articlesAreas: "مقالات عن المناطق",
  },
  it: {
    nav: ["Mappa", "Progetti", "Confronta", "Mercato", "Developer", "Calcolatore"],
    menu: "Menu",
    close: "Chiudi",
    home: "Home",
    eyebrow: "Intelligence off-plan a Dubai",
    titleA: "Vedi l'affare.",
    titleB: "Non il discorso di vendita.",
    intro: "Cerca, filtra e confronta i progetti off-plan di Dubai in un unico riferimento.",
    explore: "Esplora i progetti",
    compare: "Confronta",
    search: "Cerca progetto, developer o zona",
    allAreas: "Tutte le zone",
    allDevelopers: "Tutti i developer",
    projects: "Progetti",
    developers: "Developer",
    areas: "Zone",
    verified: "Escrow verificato",
    comparison: "Confronto live",
    comparisonSub: "Seleziona fino a 5 progetti e confronta i dati essenziali.",
    emptyCompare: "Aggiungi progetti dalla pagina progetti per iniziare.",
    goToProjects: "Vai ai progetti",
    market: "Benchmark delle zone",
    marketSub: "Riferimenti indicativi del file, non una valutazione.",
    developerTitle: "Scorecard developer",
    developerSub: "Consegna, qualità e sicurezza in una vista strutturata.",
    leadTitle: "Vuoi una shortlist per il tuo budget?",
    leadSub: "Condividi i dettagli e Mashhour Real Estate preparerà il confronto.",
    send: "Richiedi shortlist",
    success: "Grazie — la tua richiesta è pronta.",
    mapTitle: "Mappa progetti Dubai",
    mapSub: "Esplora le comunità e apri ogni progetto per tutti i dettagli.",
    mapMapped: "ZONA SELEZIONATA",
    mapHint: "Seleziona un gruppo di progetti sulla mappa.",
    mapEmpty: "I punti indicano il centro della comunità, non i confini del lotto.",
    loading: "Caricamento dati di mercato…",
    results: "risultati",
    loadMore: "Mostra altri progetti",
    viewDetails: "Dettagli",
    addCompare: "Confronta",
    selected: "Selezionato",
    maxSelected: "5 selezionati",
    exploreSections: "Esplora la piattaforma",
    exploreSectionsSub: "Ogni sezione ha ora la sua pagina.",
    sectionBlurbs: {
      map: "Individua tutte le comunità mappate a Dubai.",
      projects: "Cerca e filtra l'intero database off-plan.",
      compare: "Metti a confronto fino a cinque progetti.",
      market: "Benchmark di prezzo al piede quadro e rendimenti.",
      developers: "Punteggi di consegna, qualità e sicurezza.",
      roi: "Calcola ROI, ROE e payback di ogni unità.",
    },
    name: "Nome",
    phone: "Telefono",
    email: "Email",
    budget: "Budget",
    footerLine: "Confronto off-plan a Dubai e market intelligence.",
    roiTitle: "Calcolatore ROI e ROE",
    roiSub: "Modifica i dati e i risultati si aggiornano subito.",
    calcInputs: "Dati dell'unità",
    calcAreaSqft: "Superficie (piedi²)",
    calcPricePerSqft: "Prezzo al piede² (AED)",
    calcRentPerSqft: "Affitto annuo al piede² (AED)",
    calcAppreciation: "Rivalutazione attesa (%)",
    calcExpenses: "Spese annue (facoltativo)",
    calcUseBenchmark: "Precompila da un benchmark di zona",
    calcPlan: "Piano di pagamento",
    calcStage: "Fase",
    calcPercent: "%",
    calcAmount: "Importo",
    calcEquity: "Conta come capitale",
    calcAddStage: "Aggiungi fase",
    calcRemove: "Rimuovi",
    calcTotal: "Totale",
    calcPlanOk: "Piano di pagamento corretto ✓",
    calcPlanError: "Il piano di pagamento deve totalizzare 100%",
    calcSummary: "Riepilogo investimento",
    calcPrice: "Prezzo immobile",
    calcAnnualRent: "Affitto annuo",
    calcNetRent: "Affitto netto annuo",
    calcProjected: "Valore previsto (1 anno)",
    calcGain: "Plusvalenza",
    calcReturns: "Rendimenti e proiezione",
    calcRoi: "ROI — rendimento locativo",
    calcEquityPaid: "Capitale versato",
    calcRoe: "ROE — rendimento sul capitale",
    calcTotalReturn: "Rendimento totale anno 1",
    calcPayback: "Periodo di rientro",
    calcYears: "anni",
    calcReset: "Reimposta",
    calcFormulas: "Come viene calcolato",
    calcF1: "Prezzo = Superficie × Prezzo al piede²",
    calcF2: "Affitto annuo = Superficie × Affitto al piede²",
    calcF3: "ROI = Affitto netto ÷ Prezzo immobile",
    calcF4: "ROE = Affitto netto ÷ Capitale versato",
    calcF5: "Rientro = Capitale versato ÷ Affitto netto",
    calcNote: "Solo stime indicative. Verifica prezzi, affitti e condizioni di pagamento con il developer.",
    articlesProjects: "Approfondimenti sui progetti",
    articlesDevelopers: "Approfondimenti sui developer",
    articlesAreas: "Approfondimenti sulle zone",
  },
} satisfies Record<Lang, Record<string, unknown>>;

export type Copy = (typeof copy)["en"];
