import type { Lang } from "./types";

export const ROUTES = [
  { href: "/map", key: "map" },
  { href: "/projects", key: "projects" },
  { href: "/compare", key: "compare" },
  { href: "/market", key: "market" },
  { href: "/developers", key: "developers" },
] as const;

export const copy = {
  en: {
    nav: ["Map", "Projects", "Compare", "Market", "Developers"],
    menu: "Menu",
    close: "Close",
    home: "Home",
    eyebrow: "Dubai off-plan intelligence",
    titleA: "See the deal.",
    titleB: "Not the sales pitch.",
    intro:
      "Search, filter and compare Dubai off-plan projects using one structured market reference.",
    explore: "Explore projects",
    compare: "Compare projects",
    search: "Search by project, developer or area",
    allAreas: "All areas",
    allDevelopers: "All developers",
    projects: "Projects",
    developers: "Developers",
    areas: "Area benchmarks",
    verified: "Escrow matched",
    comparison: "Live comparison",
    comparisonSub: "Select up to 5 projects. The clearest differences stay visible.",
    emptyCompare: "Add projects from the projects page to start comparing.",
    goToProjects: "Go to projects",
    market: "Dubai area benchmarks",
    marketSub: "Indicative reference points from the workbook, not a valuation.",
    developerTitle: "Developer scorecard",
    developerSub: "A structured view of delivery, quality and safety.",
    leadTitle: "Need a shortlist built around your budget?",
    leadSub: "Share the basics and Mashhour Real Estate will prepare a focused comparison.",
    send: "Request a shortlist",
    success: "Thank you — your request is ready for follow-up.",
    mapTitle: "Dubai project map",
    mapSub: "Explore mapped communities, then open any project for the complete record.",
    mapMapped: "SELECTED AREA",
    mapHint: "Select a project cluster on the map.",
    mapEmpty: "Pins use community centres and are indicative, not plot boundaries.",
    loading: "Loading market data…",
    results: "results",
    loadMore: "Load more projects",
    viewDetails: "View details",
    addCompare: "Compare",
    selected: "Selected",
    maxSelected: "5 selected",
    exploreSections: "Explore the platform",
    exploreSectionsSub: "Each section now has its own page.",
    sectionBlurbs: {
      map: "Locate every mapped community across Dubai.",
      projects: "Search and filter the full off-plan database.",
      compare: "Put up to five projects side by side.",
      market: "Benchmark price per square foot and yields.",
      developers: "Delivery, quality and safety scores.",
    },
    name: "Name",
    phone: "Phone",
    email: "Email",
    budget: "Budget",
    footerLine: "Dubai off-plan comparison & market intelligence.",
  },
  ar: {
    nav: ["الخريطة", "المشاريع", "المقارنة", "السوق", "المطورون"],
    menu: "القائمة",
    close: "إغلاق",
    home: "الرئيسية",
    eyebrow: "مرجع الأوف بلان في دبي",
    titleA: "شوف الصفقة.",
    titleB: "مش كلام المبيعات.",
    intro: "ابحث وفلتر وقارن مشاريع دبي الأوف بلان من قاعدة بيانات منظمة واحدة.",
    explore: "استكشف المشاريع",
    compare: "قارن المشاريع",
    search: "ابحث بالمشروع أو المطور أو المنطقة",
    allAreas: "كل المناطق",
    allDevelopers: "كل المطورين",
    projects: "مشروع",
    developers: "مطور",
    areas: "مؤشر منطقة",
    verified: "حساب ضمان مطابق",
    comparison: "مقارنة مباشرة",
    comparisonSub: "اختار لحد 5 مشاريع وشوف الفروق الأساسية بوضوح.",
    emptyCompare: "ضيف مشاريع من صفحة المشاريع علشان تبدأ المقارنة.",
    goToProjects: "روح لصفحة المشاريع",
    market: "مؤشرات مناطق دبي",
    marketSub: "مؤشرات استرشادية من الشيت وليست تقييمًا عقاريًا.",
    developerTitle: "تقييم المطورين",
    developerSub: "نظرة منظمة على التسليم والجودة والأمان.",
    leadTitle: "محتاج قائمة مشاريع مناسبة لميزانيتك؟",
    leadSub: "سيب بياناتك وMashhour Real Estate يجهز لك مقارنة مركزة.",
    send: "اطلب القائمة",
    success: "شكرًا — طلبك جاهز للمتابعة.",
    mapTitle: "خريطة مشاريع دبي",
    mapSub: "استكشف المناطق واضغط على أي مشروع لفتح كل بياناته.",
    mapMapped: "المنطقة المختارة",
    mapHint: "اختار تجمع مشاريع من الخريطة.",
    mapEmpty: "النقاط في مراكز المناطق استرشادية وليست حدود قطع الأراضي.",
    loading: "جاري تحميل بيانات السوق…",
    results: "نتيجة",
    loadMore: "عرض مشاريع أكثر",
    viewDetails: "عرض التفاصيل",
    addCompare: "قارن",
    selected: "تمت الإضافة",
    maxSelected: "5 مختارة",
    exploreSections: "استكشف المنصة",
    exploreSectionsSub: "كل قسم أصبح له صفحة مستقلة.",
    sectionBlurbs: {
      map: "حدد كل المناطق على خريطة دبي.",
      projects: "ابحث وفلتر قاعدة بيانات الأوف بلان كاملة.",
      compare: "قارن حتى خمسة مشاريع جنبًا إلى جنب.",
      market: "مؤشرات سعر القدم والعائد لكل منطقة.",
      developers: "درجات التسليم والجودة والأمان.",
    },
    name: "الاسم",
    phone: "رقم الهاتف",
    email: "البريد الإلكتروني",
    budget: "الميزانية",
    footerLine: "مقارنة مشاريع دبي الأوف بلان ومؤشرات السوق.",
  },
  it: {
    nav: ["Mappa", "Progetti", "Confronta", "Mercato", "Developer"],
    menu: "Menu",
    close: "Chiudi",
    home: "Home",
    eyebrow: "Intelligence off-plan a Dubai",
    titleA: "Vedi l'affare.",
    titleB: "Non il discorso di vendita.",
    intro: "Cerca, filtra e confronta i progetti off-plan di Dubai in un unico riferimento.",
    explore: "Esplora i progetti",
    compare: "Confronta",
    search: "Cerca progetto, developer o zona",
    allAreas: "Tutte le zone",
    allDevelopers: "Tutti i developer",
    projects: "Progetti",
    developers: "Developer",
    areas: "Zone",
    verified: "Escrow verificato",
    comparison: "Confronto live",
    comparisonSub: "Seleziona fino a 5 progetti e confronta i dati essenziali.",
    emptyCompare: "Aggiungi progetti dalla pagina progetti per iniziare.",
    goToProjects: "Vai ai progetti",
    market: "Benchmark delle zone",
    marketSub: "Riferimenti indicativi del file, non una valutazione.",
    developerTitle: "Scorecard developer",
    developerSub: "Consegna, qualità e sicurezza in una vista strutturata.",
    leadTitle: "Vuoi una shortlist per il tuo budget?",
    leadSub: "Condividi i dettagli e Mashhour Real Estate preparerà il confronto.",
    send: "Richiedi shortlist",
    success: "Grazie — la tua richiesta è pronta.",
    mapTitle: "Mappa progetti Dubai",
    mapSub: "Esplora le comunità e apri ogni progetto per tutti i dettagli.",
    mapMapped: "ZONA SELEZIONATA",
    mapHint: "Seleziona un gruppo di progetti sulla mappa.",
    mapEmpty: "I punti indicano il centro della comunità, non i confini del lotto.",
    loading: "Caricamento dati di mercato…",
    results: "risultati",
    loadMore: "Mostra altri progetti",
    viewDetails: "Dettagli",
    addCompare: "Confronta",
    selected: "Selezionato",
    maxSelected: "5 selezionati",
    exploreSections: "Esplora la piattaforma",
    exploreSectionsSub: "Ogni sezione ha ora la sua pagina.",
    sectionBlurbs: {
      map: "Individua tutte le comunità mappate a Dubai.",
      projects: "Cerca e filtra l'intero database off-plan.",
      compare: "Metti a confronto fino a cinque progetti.",
      market: "Benchmark di prezzo al piede quadro e rendimenti.",
      developers: "Punteggi di consegna, qualità e sicurezza.",
    },
    name: "Nome",
    phone: "Telefono",
    email: "Email",
    budget: "Budget",
    footerLine: "Confronto off-plan a Dubai e market intelligence.",
  },
} satisfies Record<Lang, Record<string, unknown>>;

export type Copy = (typeof copy)["en"];
